# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    branches:
      only:
        - Assignment7_PJ
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6-jessie
      # CircleCI maintains a library of pre-built images
     

    working_directory: ~/repo

    steps:
      - checkout


      - run:
          name: install dependencies
          command: |
            sudo apt-get update && sudo apt-get install wget zip unzip
            python3 -m venv venv
            . venv/bin/activate
      - run:
          name: install awscli
          command: sudo pip install awscli

      - run:
          name: Download packer
          command: |
            wget -q https://releases.hashicorp.com/packer/1.4.2/packer_1.4.2_linux_amd64.zip
            unzip packer*.zip
            chmod +x packer
      - run:
          name: Build AMI
          command: |
            ./packer build \
            -var "aws_region=${AWS_REGION}" \
            -var "aws_access_key_id=${AWS_ACCESS_KEY_ID}" \
            -var "aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}" \
             ami_template.json